# _config.yml
title: "Procedura Blog"
description: "Exploring Standard Operating Procedures, Process Automation, and the Future of Workflow Management"
author: "Rickard Hultgren"
#email: "contact@procedura.dev"
baseurl: "/procedura-blog"
url: "https://rickardhultgren.github.io"
theme: minima

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Plugins
#plugins:
#  - jekyll-feed
#  - jekyll-sitemap
#  - jekyll-seo-tag

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Site settings
timezone: Europe/Stockholm
future: false
show_excerpts: true

# Social
linkedin_username: https://www.linkedin.com/in/rickard-hultgren-639000109/
github_username: https://github.com/RickardHultgren
